### ISSUE TITLE
[Suggestion] - Bonus Drops w/ Looting Enchantment

### ISSUE THREAD

**Issue by Tursiops-G** [Khazoda/beef-and-blade#3]
Drops when using a Sword w/ Looting enchantment: 
Leather: 2-3 (Unchanged)
Beef: 1 per level of enchantment (or x% Chance of/Up To 3)

Drops when using an Axe w/ Looting enchantment:
Beef: 4-5 (Unchanged)
Leather: 1 per level of enchantment (or x% Chance of/Up To 3)

-Just a Thought... ;)

**Comment by khazoda** [comment]
Fixed in dfe82b4

Thanks to Mojang making more things data-driven, this mod can now exist entirely as a 1-file datapack. Looting rules now follow vanilla behaviour for sword drops, axe drops and default drops.

Thanks for the bug report and apologies it took so long.
